[dataset]
city = "chicago"
name = "synthetic800k"
dir = "~/sparcle-exp/data/chicago-synthetic800k"

epochs = 3
attrs = ["pd", "ward", "zipcode", "beat", "ct"]


[evaluation]
eval_attrs = ["pd", "ward", "zipcode", "beat", "ct"]
file_name = "synthetic800k_hc.csv"