[dataset]
city = "chicago"
name = "synthetic"
dir = "~/sparcle-exp/data/chicago-synthetic"

epochs = 3
attrs = ["pd", "ward", "zipcode", "beat", "ct"]


[evaluation]
eval_attrs = ["pd", "ward", "zipcode", "beat", "ct"]
file_name = "synthetic_hc.csv"