[dataset]
city = "chicago"
name = "synthetic1000k"
dir = "~/sparcle-exp/data/chicago-synthetic1000k"

epochs = 3
attrs = ["pd", "ward", "zipcode"]


[evaluation]
eval_attrs = ["pd", "ward", "zipcode"]
file_name = "synthetic1000k_hc.csv"