[dataset]
city = "chicago"
name = "synthetic400k"
dir = "~/sparcle-exp/data/chicago-synthetic400k"

epochs = 3
attrs = ["pd", "ward", "zipcode"]


[evaluation]
eval_attrs = ["pd", "ward", "zipcode"]
file_name = "synthetic400k_hc.csv"