[dataset]
city = "chicago"
name = "synthetic33dr"
dir = "~/sparcle-exp/data/chicago-synthetic33dr"

epochs = 3
attrs = ["pd", "ward", "zipcode", "beat", "ct"]


[evaluation]
eval_attrs = ["pd", "ward", "zipcode", "beat", "ct"]
file_name = "synthetic33dr_hc.csv"