[dataset]
city = "chicago"
name = "synthetic700k"
dir = "~/sparcle-exp/data/chicago-synthetic700k"

epochs = 3
attrs = ["pd", "ward", "zipcode"]


[evaluation]
eval_attrs = ["pd", "ward", "zipcode"]
file_name = "synthetic700k_hc.csv"