[dataset]
city = "chicago"
name = "synthetic100k"
dir = "~/sparcle-exp/data/chicago-synthetic100k"

epochs = 3
attrs = ["pd", "ward", "zipcode", "beat", "ct"]


[evaluation]
eval_attrs = ["pd", "ward", "zipcode", "beat", "ct"]
file_name = "synthetic100k_hc.csv"